# Generated by Django 4.2 on 2023-04-08 07:11
# 0001_initial.py is the first migration file that django creates when we run the command:
# python manage.py makemigrations
# this command is used to create the tables in the database for all the apps in the project
# the migration files
# - is stored in the migrations folder of the app.
# - are used to create the tables in the database for the app.  
# - are also used to update the tables in the database when we make changes to the models.py file of the app.
# - are also used to delete the tables in the database when we delete the app from the project.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('album_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=250)),
                ('album_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('song_title', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
        ),
    ]
