# Generated by Django 4.2 on 2023-04-15 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='album_logo_url',
        ),
        migrations.AddField(
            model_name='album',
            name='album_logo_file',
            field=models.FileField(default=datetime.datetime(2023, 4, 15, 6, 58, 24, 733057, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
