# Generated by Django 4.2 on 2023-04-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_album_logo_album_album_logo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo_file',
        ),
    ]
